spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/department_db
#    username: root
#    password: Krithik2020
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#
#    show-sql: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
