
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/employee_db
#    username: root
#    password: Krithik2020
  application:
    name: EMPLOYEE-SERVICE
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  config:
    import: optional:configserver:http://localhost:8888
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#server:
#  port: 8081