
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: Krithik@2020
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081