
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/employee_db
#    username: root
#    password: Krithik2020
  application:
    name: EMPLOYEE-SERVICE
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  config:
    import: optional:configserver:http://localhost:8888


  cloud:
    compatibility-verifier:
      enabled: false
#Actuator Endpoints for Circuit backer
management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
#Circute Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  #retry Configuration
  retry:
    instances:
      EMPLOYEE-SERVICE:
        max-attempts: 5
        wait-duration: 2s




#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#server:
#  port: 8081